insert into cities (city, country) values ('Mölndal', 'Sweden');
insert into cities (city, country) values ('Vargön', 'Sweden');
insert into cities (city, country) values ('Mölnlycke', 'Sweden');
insert into cities (city, country) values ('Latakia', 'Syria');
insert into cities (city, country) values ('Sevilla', 'Spain');
insert into cities (city, country) values ('Carpentras', 'France');
insert into cities (city, country) values ('Gap', 'France');
insert into cities (city, country) values ('Hisings Kärra', 'Sweden');
insert into cities (city, country) values ('Loimaan Kunta', 'Finland');
insert into cities (city, country) values ('Roanoke', 'United States');
insert into cities (city, country) values ('Osby', 'Sweden');
insert into cities (city, country) values ('Vanáton', 'Greece');
insert into cities (city, country) values ('Saltsjöbaden', 'Sweden');
insert into cities (city, country) values ('Salamanca', 'Spain');
insert into cities (city, country) values ('Pelasgía', 'Greece');
insert into cities (city, country) values ('Santa Barbara', 'United States');
insert into cities (city, country) values ('Bankeryd', 'Sweden');
insert into cities (city, country) values ('Bernay', 'France');
insert into cities (city, country) values ('Pórto Chéli', 'Greece');
insert into cities (city, country) values ('Limeil-Brévannes', 'France');
insert into cities (city, country) values ('Sarpsborg', 'Norway');
insert into cities (city, country) values ('Kolympári', 'Greece');
insert into cities (city, country) values ('Zevgolateió', 'Greece');
insert into cities (city, country) values ('Paris', 'France');
insert into cities (city, country) values ('Dimitsána', 'Greece');
insert into cities (city, country) values ('Coutances', 'France');
insert into cities (city, country) values ('Älvsjö', 'Sweden');
insert into cities (city, country) values ('Huntsville', 'United States');
insert into cities (city, country) values ('Rouen', 'France');
insert into cities (city, country) values ('Landskrona', 'Sweden');
insert into cities (city, country) values ('Pyhäranta', 'Finland');
insert into cities (city, country) values ('Dillenburg', 'Germany');
insert into cities (city, country) values ('Béziers', 'France');
insert into cities (city, country) values ('Korydallós', 'Greece');
insert into cities (city, country) values ('Skara', 'Sweden');
insert into cities (city, country) values ('Strängnäs', 'Sweden');
insert into cities (city, country) values ('Clisson', 'France');
insert into cities (city, country) values ('Hamburg Harvestehude', 'Germany');
insert into cities (city, country) values ('Sölvesborg', 'Sweden');
insert into cities (city, country) values ('Wilkes Barre', 'United States');
insert into cities (city, country) values ('Aigínio', 'Greece');
insert into cities (city, country) values ('Lidköping', 'Sweden');
insert into cities (city, country) values ('Vallauris', 'France');
insert into cities (city, country) values ('Agía Varvára', 'Greece');
insert into cities (city, country) values ('Billings', 'United States');
insert into cities (city, country) values ('Provins', 'France');
insert into cities (city, country) values ('Drosiá', 'Greece');
insert into cities (city, country) values ('Leipsoí', 'Greece');
insert into cities (city, country) values ('Kuhmalahti', 'Finland');
insert into cities (city, country) values ('Pyhäsalmi', 'Finland');
insert into cities (city, country) values ('Liverpool', 'United Kingdom');
insert into cities (city, country) values ('Kiihtelysvaara', 'Finland');
insert into cities (city, country) values ('Pyrgetós', 'Greece');
insert into cities (city, country) values ('Neochóri', 'Greece');
insert into cities (city, country) values ('Periyiáli', 'Greece');
insert into cities (city, country) values ('Argentan', 'France');
insert into cities (city, country) values ('Kiukainen', 'Finland');
insert into cities (city, country) values ('Lansing', 'United States');
insert into cities (city, country) values ('Kvänum', 'Sweden');
insert into cities (city, country) values ('Reisjärvi', 'Finland');
insert into cities (city, country) values ('Tulsa', 'United States');
insert into cities (city, country) values ('Nykvarn', 'Sweden');
insert into cities (city, country) values ('Narbonne', 'France');
insert into cities (city, country) values ('Vrakháti', 'Greece');
insert into cities (city, country) values ('Noailles', 'France');
insert into cities (city, country) values ('Nakkila', 'Finland');
insert into cities (city, country) values ('Tampere', 'Finland');
insert into cities (city, country) values ('West End', 'United Kingdom');
insert into cities (city, country) values ('Vitoria-Gasteiz', 'Spain');
insert into cities (city, country) values ('Laval', 'France');
insert into cities (city, country) values ('Fresnes', 'France');
insert into cities (city, country) values ('Triandría', 'Greece');
insert into cities (city, country) values ('Marignane', 'France');
insert into cities (city, country) values ('La Rochelle', 'France');
insert into cities (city, country) values ('Tuusula', 'Finland');
insert into cities (city, country) values ('Náfplio', 'Greece');
insert into cities (city, country) values ('Rodópoli', 'Greece');
insert into cities (city, country) values ('Garland', 'United States');
insert into cities (city, country) values ('Kannus', 'Finland');
insert into cities (city, country) values ('Aulnay-sous-Bois', 'France');
insert into cities (city, country) values ('Köping', 'Sweden');
insert into cities (city, country) values ('Mosjøen', 'Norway');
insert into cities (city, country) values ('Birmingham', 'United States');
insert into cities (city, country) values ('Kävlinge', 'Sweden');
insert into cities (city, country) values ('Borås', 'Sweden');
insert into cities (city, country) values ('Port-de-Bouc', 'France');
insert into cities (city, country) values ('Ljungsbro', 'Sweden');
insert into cities (city, country) values ('Austin', 'United States');
insert into cities (city, country) values ('Allentown', 'United States');
insert into cities (city, country) values ('Canton', 'United States');
insert into cities (city, country) values ('Perístasi', 'Greece');
insert into cities (city, country) values ('Gastoúni', 'Greece');
insert into cities (city, country) values ('Cran-Gevrier', 'France');
insert into cities (city, country) values ('Bayonne', 'France');
insert into cities (city, country) values ('Götene', 'Sweden');
insert into cities (city, country) values ('Neos Voutzás', 'Greece');
insert into cities (city, country) values ('Chantilly', 'France');
insert into cities (city, country) values ('Ödeshög', 'Sweden');
insert into cities (city, country) values ('Palaiochóri', 'Greece');
insert into cities (city, country) values ('Aix-en-Provence', 'France');
insert into cities (city, country) values ('Saint-Pierre-des-Corps', 'France');
insert into cities (city, country) values ('Puteaux', 'France');
insert into cities (city, country) values ('Montargis', 'France');
insert into cities (city, country) values ('Káto Miliá', 'Greece');
insert into cities (city, country) values ('Moss', 'Norway');
insert into cities (city, country) values ('Jacksonville', 'United States');
insert into cities (city, country) values ('Elimäki', 'Finland');
insert into cities (city, country) values ('Saint-Avertin', 'France');
insert into cities (city, country) values ('Lappajärvi', 'Finland');
insert into cities (city, country) values ('Mikrókampos', 'Greece');
insert into cities (city, country) values ('Tampa', 'United States');
insert into cities (city, country) values ('Vancouver', 'United States');
insert into cities (city, country) values ('Cognac', 'France');
insert into cities (city, country) values ('Loudun', 'France');
insert into cities (city, country) values ('Ljungskile', 'Sweden');
insert into cities (city, country) values ('Hammarö', 'Sweden');
insert into cities (city, country) values ('Goussainville', 'France');
insert into cities (city, country) values ('Pueblo', 'United States');
insert into cities (city, country) values ('Sumiainen', 'Finland');
insert into cities (city, country) values ('Montreuil', 'France');
insert into cities (city, country) values ('Sartrouville', 'France');
insert into cities (city, country) values ('Borgholm', 'Sweden');
insert into cities (city, country) values ('Huskvarna', 'Sweden');
insert into cities (city, country) values ('Ford', 'United Kingdom');
insert into cities (city, country) values ('Kinéta', 'Greece');
insert into cities (city, country) values ('Igoumenítsa', 'Greece');
insert into cities (city, country) values ('Karlstad', 'Sweden');
insert into cities (city, country) values ('Bålsta', 'Sweden');
insert into cities (city, country) values ('La Garde', 'France');
insert into cities (city, country) values ('Rizómilos', 'Greece');
insert into cities (city, country) values ('Shawnee Mission', 'United States');
insert into cities (city, country) values ('Replot', 'Finland');
insert into cities (city, country) values ('Erie', 'United States');
insert into cities (city, country) values ('Sievi', 'Finland');
insert into cities (city, country) values ('Lapinjärvi', 'Finland');
insert into cities (city, country) values ('Pensacola', 'United States');
insert into cities (city, country) values ('Lafayette', 'United States');
insert into cities (city, country) values ('Fontenay-sous-Bois', 'France');
insert into cities (city, country) values ('Châtellerault', 'France');
insert into cities (city, country) values ('Angoulême', 'France');
insert into cities (city, country) values ('Steinkjer', 'Norway');
insert into cities (city, country) values ('Símantra', 'Greece');
insert into cities (city, country) values ('Néa Ionía', 'Greece');
insert into cities (city, country) values ('Carlsbad', 'United States');
insert into cities (city, country) values ('Orlando', 'United States');
insert into cities (city, country) values ('Alivéri', 'Greece');
insert into cities (city, country) values ('Badajoz', 'Spain');
insert into cities (city, country) values ('Kumla', 'Sweden');
insert into cities (city, country) values ('Siikainen', 'Finland');
insert into cities (city, country) values ('Joutseno', 'Finland');
insert into cities (city, country) values ('Bagarmossen', 'Sweden');
insert into cities (city, country) values ('Anáfi', 'Greece');
insert into cities (city, country) values ('Donostia-San Sebastian', 'Spain');
insert into cities (city, country) values ('Vernon', 'France');
insert into cities (city, country) values ('Villefranche-sur-Mer', 'France');
insert into cities (city, country) values ('Svalöv', 'Sweden');
insert into cities (city, country) values ('Porsgrunn', 'Norway');
insert into cities (city, country) values ('Frontignan', 'France');
insert into cities (city, country) values ('Tumba', 'Sweden');
insert into cities (city, country) values ('Albi', 'France');
insert into cities (city, country) values ('Irvine', 'United States');
insert into cities (city, country) values ('Charenton-le-Pont', 'France');
insert into cities (city, country) values ('Redon', 'France');
insert into cities (city, country) values ('Newport', 'United Kingdom');
insert into cities (city, country) values ('Askim', 'Norway');
insert into cities (city, country) values ('La Gacilly', 'France');
insert into cities (city, country) values ('Lindome', 'Sweden');
insert into cities (city, country) values ('Oakland', 'United States');
insert into cities (city, country) values ('Montluel', 'France');
insert into cities (city, country) values ('Psychikó', 'Greece');
insert into cities (city, country) values ('Kaparéllion', 'Greece');
insert into cities (city, country) values ('Hyltebruk', 'Sweden');
insert into cities (city, country) values ('Ålesund', 'Norway');
insert into cities (city, country) values ('Nantes', 'France');
insert into cities (city, country) values ('Saint-Grégoire', 'France');
insert into cities (city, country) values ('Claye-Souilly', 'France');
insert into cities (city, country) values ('Pamiers', 'France');
insert into cities (city, country) values ('San Francisco', 'United States');
insert into cities (city, country) values ('Topeka', 'United States');
insert into cities (city, country) values ('Fort Lauderdale', 'United States');
insert into cities (city, country) values ('Kirkton', 'United Kingdom');
insert into cities (city, country) values ('Clermont-Ferrand', 'France');
insert into cities (city, country) values ('Vallentuna', 'Sweden');
insert into cities (city, country) values ('Kalpáki', 'Greece');
insert into cities (city, country) values ('Portland', 'United States');
insert into cities (city, country) values ('Marietta', 'United States');
insert into cities (city, country) values ('Alexandria', 'United States');
insert into cities (city, country) values ('Kristianstad', 'Sweden');
insert into cities (city, country) values ('Loutrá', 'Greece');
insert into cities (city, country) values ('Ágios Vasíleios', 'Greece');
insert into cities (city, country) values ('Louisville', 'United States');
insert into cities (city, country) values ('Palma De Mallorca', 'Spain');
insert into cities (city, country) values ('Heby', 'Sweden');
insert into cities (city, country) values ('Montauban', 'France');
insert into cities (city, country) values ('Ávato', 'Greece');
insert into cities (city, country) values ('Tulle', 'France');
insert into cities (city, country) values ('Rönninge', 'Sweden');
insert into cities (city, country) values ('Gamleby', 'Sweden');
insert into cities (city, country) values ('Pessac', 'France');
insert into cities (city, country) values ('Vendargues', 'France');
insert into cities (city, country) values ('Arboga', 'Sweden');
insert into cities (city, country) values ('Xilópolis', 'Greece');
insert into cities (city, country) values ('Nynäshamn', 'Sweden');
insert into cities (city, country) values ('Helsingborg', 'Sweden');
insert into cities (city, country) values ('Cadiz', 'Spain');
insert into cities (city, country) values ('Élancourt', 'France');
insert into cities (city, country) values ('Karlskoga', 'Sweden');
insert into cities (city, country) values ('Houston', 'United States');
insert into cities (city, country) values ('Futuroscope', 'France');
insert into cities (city, country) values ('Vilhelmina', 'Sweden');
insert into cities (city, country) values ('Mýki', 'Greece');
insert into cities (city, country) values ('Kréstena', 'Greece');
insert into cities (city, country) values ('Saint-Quentin', 'France');
insert into cities (city, country) values ('Ystad', 'Sweden');
insert into cities (city, country) values ('Ruokolahti', 'Finland');
insert into cities (city, country) values ('Áyios Vasílios', 'Greece');
insert into cities (city, country) values ('Nice', 'France');
insert into cities (city, country) values ('Oskarshamn', 'Sweden');
insert into cities (city, country) values ('Grästorp', 'Sweden');
insert into cities (city, country) values ('Torsby', 'Sweden');
insert into cities (city, country) values ('Minneapolis', 'United States');
insert into cities (city, country) values ('Pentéli', 'Greece');
insert into cities (city, country) values ('Palaiomonástiron', 'Greece');
insert into cities (city, country) values ('Sheffield', 'United Kingdom');
insert into cities (city, country) values ('Utajärvi', 'Finland');
insert into cities (city, country) values ('Methóni', 'Greece');
insert into cities (city, country) values ('Bradford', 'United Kingdom');
insert into cities (city, country) values ('Próchoma', 'Greece');
insert into cities (city, country) values ('Chattanooga', 'United States');
insert into cities (city, country) values ('Lidingö', 'Sweden');
insert into cities (city, country) values ('Charleston', 'United States');
insert into cities (city, country) values ('Santa Ana', 'United States');
insert into cities (city, country) values ('Braunschweig', 'Germany');
insert into cities (city, country) values ('Valencia', 'Spain');
insert into cities (city, country) values ('Newark', 'United States');
insert into cities (city, country) values ('Sandnes', 'Norway');
insert into cities (city, country) values ('Villeneuve-d''Ascq', 'France');
insert into cities (city, country) values ('Filótion', 'Greece');
insert into cities (city, country) values ('Harjavalta', 'Finland');
insert into cities (city, country) values ('Växjö', 'Sweden');
insert into cities (city, country) values ('Santander', 'Spain');
insert into cities (city, country) values ('Leonídio', 'Greece');
insert into cities (city, country) values ('Colorado Springs', 'United States');
insert into cities (city, country) values ('Åstorp', 'Sweden');
insert into cities (city, country) values ('Savonranta', 'Finland');
insert into cities (city, country) values ('Port Washington', 'United States');
insert into cities (city, country) values ('Peoria', 'United States');
insert into cities (city, country) values ('Sápes', 'Greece');
insert into cities (city, country) values ('Yläne', 'Finland');
insert into cities (city, country) values ('Messina', 'Italy');
insert into cities (city, country) values ('Girona', 'Spain');
insert into cities (city, country) values ('Kilkís', 'Greece');
insert into cities (city, country) values ('Domsjö', 'Sweden');
insert into cities (city, country) values ('London', 'United Kingdom');
insert into cities (city, country) values ('Rodotópi', 'Greece');
insert into cities (city, country) values ('Lápas', 'Greece');
insert into cities (city, country) values ('Guilherand-Granges', 'France');
insert into cities (city, country) values ('Nanterre', 'France');
insert into cities (city, country) values ('Argithéa', 'Greece');
insert into cities (city, country) values ('Puget-sur-Argens', 'France');
insert into cities (city, country) values ('Palmas De Gran Canaria, Las', 'Spain');
insert into cities (city, country) values ('Arlöv', 'Sweden');
insert into cities (city, country) values ('Savitaipale', 'Finland');
insert into cities (city, country) values ('Indianapolis', 'United States');
insert into cities (city, country) values ('Hagondange', 'France');
insert into cities (city, country) values ('Bodø', 'Norway');
insert into cities (city, country) values ('Schiltigheim', 'France');
insert into cities (city, country) values ('Norsborg', 'Sweden');
insert into cities (city, country) values ('Skutskär', 'Sweden');
insert into cities (city, country) values ('Alingsås', 'Sweden');
insert into cities (city, country) values ('Spárti', 'Greece');
insert into cities (city, country) values ('Twyford', 'United Kingdom');
insert into cities (city, country) values ('Wasquehal', 'France');
insert into cities (city, country) values ('Savannah', 'United States');
insert into cities (city, country) values ('Sélestat', 'France');
insert into cities (city, country) values ('Saint-Lô', 'France');
insert into cities (city, country) values ('Romorantin-Lanthenay', 'France');
insert into cities (city, country) values ('Farmington', 'United States');
insert into cities (city, country) values ('Dortmund', 'Germany');
insert into cities (city, country) values ('Arvika', 'Sweden');
insert into cities (city, country) values ('Brétigny-sur-Orge', 'France');
insert into cities (city, country) values ('Bourges', 'France');
insert into cities (city, country) values ('Youngstown', 'United States');
insert into cities (city, country) values ('Vihti', 'Finland');
insert into cities (city, country) values ('Nashville', 'United States');
insert into cities (city, country) values ('Chambéry', 'France');
insert into cities (city, country) values ('Muskegon', 'United States');
insert into cities (city, country) values ('Nerokoúros', 'Greece');
insert into cities (city, country) values ('Skanör', 'Sweden');
insert into cities (city, country) values ('Châlons-en-Champagne', 'France');
insert into cities (city, country) values ('Pau', 'France');
insert into cities (city, country) values ('Castellon De La Plana/Castello De La Pla', 'Spain');
insert into cities (city, country) values ('Denver', 'United States');
insert into cities (city, country) values ('Östersund', 'Sweden');
insert into cities (city, country) values ('Mobile', 'United States');
insert into cities (city, country) values ('Tarvasjoki', 'Finland');
insert into cities (city, country) values ('Simrishamn', 'Sweden');
insert into cities (city, country) values ('Töreboda', 'Sweden');
insert into cities (city, country) values ('Épinal', 'France');
insert into cities (city, country) values ('Reading', 'United States');
insert into cities (city, country) values ('Atlanta', 'United States');
insert into cities (city, country) values ('Fílla', 'Greece');
insert into cities (city, country) values ('Axioúpoli', 'Greece');
insert into cities (city, country) values ('Toledo', 'Spain');
insert into cities (city, country) values ('Kalávryta', 'Greece');
insert into cities (city, country) values ('Íasmos', 'Greece');
insert into cities (city, country) values ('Cernay', 'France');
insert into cities (city, country) values ('Stylída', 'Greece');
insert into cities (city, country) values ('Angered', 'Sweden');
insert into cities (city, country) values ('Leganes', 'Spain');
insert into cities (city, country) values ('Palaió Fáliro', 'Greece');
insert into cities (city, country) values ('Langres', 'France');
insert into cities (city, country) values ('Évreux', 'France');
insert into cities (city, country) values ('Saint-Quentin-Fallavier', 'France');
insert into cities (city, country) values ('Vanves', 'France');
insert into cities (city, country) values ('Lescar', 'France');
insert into cities (city, country) values ('Roissy Charles-de-Gaulle', 'France');
insert into cities (city, country) values ('Eslöv', 'Sweden');
insert into cities (city, country) values ('Blois', 'France');
insert into cities (city, country) values ('Hamburg', 'Germany');
insert into cities (city, country) values ('San Jose', 'United States');
insert into cities (city, country) values ('Xinó Neró', 'Greece');
insert into cities (city, country) values ('Issy-les-Moulineaux', 'France');
insert into cities (city, country) values ('Marne-la-Vallée', 'France');
insert into cities (city, country) values ('Norfolk', 'United States');
insert into cities (city, country) values ('Kissimmee', 'United States');
insert into cities (city, country) values ('Rambouillet', 'France');
insert into cities (city, country) values ('Odessa', 'United States');
insert into cities (city, country) values ('Skýros', 'Greece');
insert into cities (city, country) values ('Järfälla', 'Sweden');
insert into cities (city, country) values ('Milton', 'United Kingdom');
insert into cities (city, country) values ('Peraía', 'Greece');
insert into cities (city, country) values ('New York City', 'United States');
insert into cities (city, country) values ('Koufália', 'Greece');
insert into cities (city, country) values ('Upton', 'United Kingdom');
insert into cities (city, country) values ('Magdeburg', 'Germany');
insert into cities (city, country) values ('Villeneuve-sur-Lot', 'France');
insert into cities (city, country) values ('Limenária', 'Greece');
insert into cities (city, country) values ('Malax', 'Finland');
insert into cities (city, country) values ('Tyresö', 'Sweden');
insert into cities (city, country) values ('Skövde', 'Sweden');
insert into cities (city, country) values ('Montceau-les-Mines', 'France');
insert into cities (city, country) values ('Witzenhausen', 'Germany');
insert into cities (city, country) values ('Bronx', 'United States');
insert into cities (city, country) values ('Enköping', 'Sweden');
insert into cities (city, country) values ('Trelleborg', 'Sweden');
insert into cities (city, country) values ('La Plaine-Saint-Denis', 'France');
insert into cities (city, country) values ('Dijon', 'France');
insert into cities (city, country) values ('Molsheim', 'France');
insert into cities (city, country) values ('Zamora', 'Spain');
insert into cities (city, country) values ('Cesson-Sévigné', 'France');
insert into cities (city, country) values ('Newton', 'United States');
insert into cities (city, country) values ('Mayenne', 'France');
insert into cities (city, country) values ('Edsbyn', 'Sweden');
insert into cities (city, country) values ('Challans', 'France');
insert into cities (city, country) values ('Detroit', 'United States');
insert into cities (city, country) values ('Avon', 'France');
insert into cities (city, country) values ('Nacka', 'Sweden');
insert into cities (city, country) values ('Noyal-sur-Vilaine', 'France');
insert into cities (city, country) values ('Burnside', 'United Kingdom');
insert into cities (city, country) values ('Saint-Dizier', 'France');
insert into cities (city, country) values ('Antony', 'France');
insert into cities (city, country) values ('Flen', 'Sweden');
insert into cities (city, country) values ('Varberg', 'Sweden');
insert into cities (city, country) values ('Gouménissa', 'Greece');
insert into cities (city, country) values ('Montaigu', 'France');
insert into cities (city, country) values ('Elmira', 'United States');
insert into cities (city, country) values ('Eskilstuna', 'Sweden');
insert into cities (city, country) values ('Kangaslampi', 'Finland');
insert into cities (city, country) values ('Rennes', 'France');
insert into cities (city, country) values ('Gary', 'United States');
insert into cities (city, country) values ('Grand Rapids', 'United States');
insert into cities (city, country) values ('Saint-Jean-de-Luz', 'France');
insert into cities (city, country) values ('Kalloní', 'Greece');
insert into cities (city, country) values ('Pittsburgh', 'United States');
insert into cities (city, country) values ('Tours', 'France');
insert into cities (city, country) values ('Strasbourg', 'France');
insert into cities (city, country) values ('Storuman', 'Sweden');
insert into cities (city, country) values ('Sundsvall', 'Sweden');
insert into cities (city, country) values ('Pásion', 'Greece');
insert into cities (city, country) values ('Bromma', 'Sweden');
insert into cities (city, country) values ('Newton', 'United Kingdom');
insert into cities (city, country) values ('Kauhava', 'Finland');
insert into cities (city, country) values ('Autun', 'France');
insert into cities (city, country) values ('Grenoble', 'France');
insert into cities (city, country) values ('Hallstahammar', 'Sweden');
insert into cities (city, country) values ('Paterson', 'United States');
insert into cities (city, country) values ('Munkfors', 'Sweden');
insert into cities (city, country) values ('Brest', 'France');
insert into cities (city, country) values ('Vrilissia', 'Greece');
insert into cities (city, country) values ('Auxerre', 'France');
insert into cities (city, country) values ('Kansas City', 'United States');
insert into cities (city, country) values ('Malaga', 'Spain');
insert into cities (city, country) values ('Fort Worth', 'United States');
insert into cities (city, country) values ('Amarillo', 'United States');
insert into cities (city, country) values ('Charlotte', 'United States');
insert into cities (city, country) values ('Providence', 'United States');
insert into cities (city, country) values ('Sandviken', 'Sweden');
insert into cities (city, country) values ('Nässjö', 'Sweden');
insert into cities (city, country) values ('Umeå', 'Sweden');
insert into cities (city, country) values ('Hollywood', 'United States');
insert into cities (city, country) values ('Lancaster', 'United States');
insert into cities (city, country) values ('Zárkos', 'Greece');
insert into cities (city, country) values ('Frei', 'Norway');
insert into cities (city, country) values ('Essen', 'Germany');
insert into cities (city, country) values ('Filipstad', 'Sweden');
insert into cities (city, country) values ('Miami', 'United States');
insert into cities (city, country) values ('Kauniainen', 'Finland');
insert into cities (city, country) values ('Frankfort', 'United States');
insert into cities (city, country) values ('Lappi', 'Finland');
insert into cities (city, country) values ('Kéfalos', 'Greece');
insert into cities (city, country) values ('Rungis', 'France');
insert into cities (city, country) values ('Psachná', 'Greece');
insert into cities (city, country) values ('Ambelón', 'Greece');
insert into cities (city, country) values ('Kostakioí', 'Greece');
insert into cities (city, country) values ('Fréjus', 'France');
insert into cities (city, country) values ('Trångsund', 'Sweden');
insert into cities (city, country) values ('Huntington', 'United States');
insert into cities (city, country) values ('Bastia', 'France');
insert into cities (city, country) values ('Memphis', 'United States');
insert into cities (city, country) values ('Dístomo', 'Greece');
insert into cities (city, country) values ('Boden', 'Sweden');
insert into cities (city, country) values ('Arnage', 'France');
insert into cities (city, country) values ('Bonneuil-sur-Marne', 'France');
insert into cities (city, country) values ('Bremen', 'Germany');
insert into cities (city, country) values ('Prámanta', 'Greece');
insert into cities (city, country) values ('Mainz', 'Germany');
insert into cities (city, country) values ('La Roche-sur-Yon', 'France');
insert into cities (city, country) values ('Lavaur', 'France');
insert into cities (city, country) values ('Fresno', 'United States');
insert into cities (city, country) values ('Jäppilä', 'Finland');
insert into cities (city, country) values ('Auch', 'France');
insert into cities (city, country) values ('Roubaix', 'France');
insert into cities (city, country) values ('Mykonos', 'Greece');
insert into cities (city, country) values ('El Paso', 'United States');
insert into cities (city, country) values ('Valence', 'France');
insert into cities (city, country) values ('Smålandsstenar', 'Sweden');
insert into cities (city, country) values ('Brooklyn', 'United States');
insert into cities (city, country) values ('Saint-Quentin-en-Yvelines', 'France');
insert into cities (city, country) values ('Älvdalen', 'Sweden');
insert into cities (city, country) values ('Leipzig', 'Germany');
insert into cities (city, country) values ('Knoxville', 'United States');
insert into cities (city, country) values ('Sérvia', 'Greece');
insert into cities (city, country) values ('Perpignan', 'France');
insert into cities (city, country) values ('Amiens', 'France');
insert into cities (city, country) values ('Turku', 'Finland');
insert into cities (city, country) values ('Mandráki', 'Greece');
insert into cities (city, country) values ('West Hartford', 'United States');
insert into cities (city, country) values ('Kassel', 'Germany');
insert into cities (city, country) values ('Salerno', 'Italy');
insert into cities (city, country) values ('Hollola', 'Finland');
insert into cities (city, country) values ('Philadelphia', 'United States');
insert into cities (city, country) values ('Scottsdale', 'United States');
insert into cities (city, country) values ('Ouranoupolis', 'Greece');
insert into cities (city, country) values ('Würzburg', 'Germany');
insert into cities (city, country) values ('Motala', 'Sweden');
insert into cities (city, country) values ('Vincennes', 'France');
insert into cities (city, country) values ('Skillingaryd', 'Sweden');
insert into cities (city, country) values ('Frederiksberg', 'Denmark');
insert into cities (city, country) values ('Salon-de-Provence', 'France');
insert into cities (city, country) values ('Caen', 'France');
insert into cities (city, country) values ('San Diego', 'United States');
insert into cities (city, country) values ('Verdun', 'France');
insert into cities (city, country) values ('Täby', 'Sweden');
insert into cities (city, country) values ('Ängelholm', 'Sweden');
insert into cities (city, country) values ('Merrifield', 'United States');
insert into cities (city, country) values ('Aurora', 'United States');
insert into cities (city, country) values ('Pyhäjoki', 'Finland');
insert into cities (city, country) values ('Tarbes', 'France');
insert into cities (city, country) values ('Trondheim', 'Norway');
insert into cities (city, country) values ('San Antonio', 'United States');
insert into cities (city, country) values ('Anchorage', 'United States');
insert into cities (city, country) values ('Nisí', 'Greece');
insert into cities (city, country) values ('Landvetter', 'Sweden');
insert into cities (city, country) values ('Skien', 'Norway');
insert into cities (city, country) values ('Alexandroúpoli', 'Greece');
insert into cities (city, country) values ('Fteliá', 'Greece');
insert into cities (city, country) values ('Los Angeles', 'United States');
insert into cities (city, country) values ('Álli Meriá', 'Greece');
insert into cities (city, country) values ('Beaune', 'France');
insert into cities (city, country) values ('Cergy-Pontoise', 'France');
insert into cities (city, country) values ('Amfíkleia', 'Greece');
insert into cities (city, country) values ('Ikaalinen', 'Finland');
insert into cities (city, country) values ('Palaiópyrgos', 'Greece');
insert into cities (city, country) values ('Joroinen', 'Finland');
insert into cities (city, country) values ('Sannois', 'France');
insert into cities (city, country) values ('Tacoma', 'United States');
insert into cities (city, country) values ('Lékhaio', 'Greece');
insert into cities (city, country) values ('Tournon-sur-Rhône', 'France');
insert into cities (city, country) values ('Imatra', 'Finland');
insert into cities (city, country) values ('Åkersberga', 'Sweden');
insert into cities (city, country) values ('Carpiquet', 'France');
insert into cities (city, country) values ('Oslo', 'Norway');
insert into cities (city, country) values ('Harrisburg', 'United States');
insert into cities (city, country) values ('Tyler', 'United States');
insert into cities (city, country) values ('Toulon', 'France');
insert into cities (city, country) values ('Laon', 'France');
insert into cities (city, country) values ('Chico', 'United States');
insert into cities (city, country) values ('Versailles', 'France');
insert into cities (city, country) values ('Cahors', 'France');
insert into cities (city, country) values ('Chrysó', 'Greece');
insert into cities (city, country) values ('Alhambra', 'United States');
insert into cities (city, country) values ('Vedène', 'France');
insert into cities (city, country) values ('Göteborg', 'Sweden');
insert into cities (city, country) values ('San Bernardino', 'United States');
insert into cities (city, country) values ('Humble', 'United States');
insert into cities (city, country) values ('Washington', 'United States');
insert into cities (city, country) values ('Fécamp', 'France');
insert into cities (city, country) values ('Ceuta', 'Spain');
insert into cities (city, country) values ('Mora', 'Sweden');
insert into cities (city, country) values ('Drammen', 'Norway');
insert into cities (city, country) values ('Boxholm', 'Sweden');
insert into cities (city, country) values ('Wiesbaden', 'Germany');
insert into cities (city, country) values ('Dresden', 'Germany');
insert into cities (city, country) values ('Kongsvinger', 'Norway');
insert into cities (city, country) values ('Örebro', 'Sweden');
insert into cities (city, country) values ('Toulouse', 'France');
insert into cities (city, country) values ('Niort', 'France');
insert into cities (city, country) values ('Karlskrona', 'Sweden');
insert into cities (city, country) values ('Falun', 'Sweden');
insert into cities (city, country) values ('Fosses', 'France');
insert into cities (city, country) values ('Chantepie', 'France');
insert into cities (city, country) values ('Milwaukee', 'United States');
insert into cities (city, country) values ('Plátanos', 'Greece');
insert into cities (city, country) values ('Jefferson City', 'United States');
insert into cities (city, country) values ('Kalajoki', 'Finland');
insert into cities (city, country) values ('Riihimäki', 'Finland');
insert into cities (city, country) values ('Sísion', 'Greece');
insert into cities (city, country) values ('Metz', 'France');
insert into cities (city, country) values ('Berlin', 'Germany');
insert into cities (city, country) values ('Reno', 'United States');
insert into cities (city, country) values ('Bagnolet', 'France');
insert into cities (city, country) values ('Kiruna', 'Sweden');
insert into cities (city, country) values ('Koropí', 'Greece');
insert into cities (city, country) values ('Mitrópoli', 'Greece');
insert into cities (city, country) values ('Moholm', 'Sweden');
insert into cities (city, country) values ('Mont-de-Marsan', 'France');
insert into cities (city, country) values ('Marseille', 'France');
insert into cities (city, country) values ('East End', 'United Kingdom');
insert into cities (city, country) values ('Fullerton', 'United States');
insert into cities (city, country) values ('Kokkári', 'Greece');
insert into cities (city, country) values ('Sandefjord', 'Norway');
insert into cities (city, country) values ('Kiikala', 'Finland');
insert into cities (city, country) values ('Laspezia', 'Italy');
insert into cities (city, country) values ('Boca Raton', 'United States');
insert into cities (city, country) values ('Daytona Beach', 'United States');
insert into cities (city, country) values ('Gävle', 'Sweden');
insert into cities (city, country) values ('Quimper', 'France');
insert into cities (city, country) values ('Ludvika', 'Sweden');
insert into cities (city, country) values ('Logroño', 'Spain');
insert into cities (city, country) values ('Saint Cloud', 'United States');
insert into cities (city, country) values ('Tierp', 'Sweden');
insert into cities (city, country) values ('Montpellier', 'France');
insert into cities (city, country) values ('Cincinnati', 'United States');
insert into cities (city, country) values ('Färjestaden', 'Sweden');
insert into cities (city, country) values ('Saint-Nazaire', 'France');
insert into cities (city, country) values ('New Brunswick', 'United States');
insert into cities (city, country) values ('Duisburg', 'Germany');
insert into cities (city, country) values ('Makrochóri', 'Greece');
insert into cities (city, country) values ('Knivsta', 'Sweden');
insert into cities (city, country) values ('Birmingham', 'United Kingdom');
insert into cities (city, country) values ('Hägersten', 'Sweden');
insert into cities (city, country) values ('Dióni', 'Greece');
insert into cities (city, country) values ('Vittel', 'France');
insert into cities (city, country) values ('Panórama', 'Greece');
insert into cities (city, country) values ('Solna', 'Sweden');
insert into cities (city, country) values ('Arnaía', 'Greece');
insert into cities (city, country) values ('Saint Augustine', 'United States');
insert into cities (city, country) values ('Gentilly', 'France');
insert into cities (city, country) values ('Néo Psychikó', 'Greece');
insert into cities (city, country) values ('Agía Triáda', 'Greece');
insert into cities (city, country) values ('Rodez', 'France');
insert into cities (city, country) values ('Lycksele', 'Sweden');
insert into cities (city, country) values ('Sens', 'France');
insert into cities (city, country) values ('Grängesberg', 'Sweden');
insert into cities (city, country) values ('Nancy', 'France');
insert into cities (city, country) values ('Haninge', 'Sweden');
insert into cities (city, country) values ('Évry', 'France');
insert into cities (city, country) values ('Pontevedra', 'Spain');
insert into cities (city, country) values ('Alès', 'France');
insert into cities (city, country) values ('Loukísia', 'Greece');
insert into cities (city, country) values ('Tullich', 'United Kingdom');
insert into cities (city, country) values ('Chartres', 'France');
insert into cities (city, country) values ('Uppsala', 'Sweden');
insert into cities (city, country) values ('Troyes', 'France');
insert into cities (city, country) values ('Dhrosiá', 'Greece');
insert into cities (city, country) values ('Tílisos', 'Greece');
insert into cities (city, country) values ('Orly', 'France');
insert into cities (city, country) values ('Dole', 'France');
insert into cities (city, country) values ('Iowa City', 'United States');
insert into cities (city, country) values ('Köln', 'Germany');
insert into cities (city, country) values ('Katrineholm', 'Sweden');
insert into cities (city, country) values ('Fargo', 'United States');
insert into cities (city, country) values ('Cumming', 'United States');
insert into cities (city, country) values ('Trollhättan', 'Sweden');
insert into cities (city, country) values ('Limoges', 'France');
insert into cities (city, country) values ('Chambray-lès-Tours', 'France');
insert into cities (city, country) values ('Springfield', 'United States');
insert into cities (city, country) values ('Carson City', 'United States');
insert into cities (city, country) values ('Höllviken', 'Sweden');
insert into cities (city, country) values ('Avignon', 'France');
insert into cities (city, country) values ('Ekerö', 'Sweden');
insert into cities (city, country) values ('Ágios Stéfanos', 'Greece');
insert into cities (city, country) values ('Markaryd', 'Sweden');
insert into cities (city, country) values ('Södertälje', 'Sweden');
insert into cities (city, country) values ('Monastirákion', 'Greece');
insert into cities (city, country) values ('Västra Frölunda', 'Sweden');
insert into cities (city, country) values ('Norrköping', 'Sweden');
insert into cities (city, country) values ('Néos Skopós', 'Greece');
insert into cities (city, country) values ('Jackson', 'United States');
insert into cities (city, country) values ('Taverny', 'France');
insert into cities (city, country) values ('Créteil', 'France');
insert into cities (city, country) values ('Lillehammer', 'Norway');
insert into cities (city, country) values ('Annecy', 'France');
insert into cities (city, country) values ('Arcueil', 'France');
insert into cities (city, country) values ('Kými', 'Greece');
insert into cities (city, country) values ('Luleå', 'Sweden');
insert into cities (city, country) values ('Chemnitz', 'Germany');
insert into cities (city, country) values ('Reims', 'France');
insert into cities (city, country) values ('Halmstad', 'Sweden');
insert into cities (city, country) values ('Saukkola', 'Finland');
insert into cities (city, country) values ('Alavus', 'Finland');
insert into cities (city, country) values ('Vinkkilä', 'Finland');
insert into cities (city, country) values ('München', 'Germany');
insert into cities (city, country) values ('Freiburg im Breisgau', 'Germany');
insert into cities (city, country) values ('Saint-Maur-des-Fossés', 'France');
insert into cities (city, country) values ('La Seyne-sur-Mer', 'France');
insert into cities (city, country) values ('Burträsk', 'Sweden');
insert into cities (city, country) values ('Strömsund', 'Sweden');
insert into cities (city, country) values ('Bordeaux', 'France');
insert into cities (city, country) values ('Dallas', 'United States');
insert into cities (city, country) values ('Kouvarás', 'Greece');
insert into cities (city, country) values ('Cannes', 'France');
insert into cities (city, country) values ('Vellinge', 'Sweden');
insert into cities (city, country) values ('Alíartos', 'Greece');
insert into cities (city, country) values ('Chicago', 'United States');
insert into cities (city, country) values ('Migrate', 'United States');
insert into cities (city, country) values ('Le Raincy', 'France');
insert into cities (city, country) values ('Tucson', 'United States');
insert into cities (city, country) values ('Bergen', 'Norway');
insert into cities (city, country) values ('Lyon', 'France');
insert into cities (city, country) values ('Rezé', 'France');
insert into cities (city, country) values ('Jönköping', 'Sweden');
insert into cities (city, country) values ('Corbeil-Essonnes', 'France');
insert into cities (city, country) values ('Arras', 'France');
insert into cities (city, country) values ('København', 'Denmark');
insert into cities (city, country) values ('Agiásos', 'Greece');
insert into cities (city, country) values ('Madison', 'United States');
insert into cities (city, country) values ('South Bend', 'United States');
insert into cities (city, country) values ('Finspång', 'Sweden');
insert into cities (city, country) values ('Jamaica', 'United States');
insert into cities (city, country) values ('Staten Island', 'United States');
insert into cities (city, country) values ('Phoenix', 'United States');
insert into cities (city, country) values ('Inglewood', 'United States');
insert into cities (city, country) values ('Áno Kastrítsion', 'Greece');
insert into cities (city, country) values ('Svenljunga', 'Sweden');
insert into cities (city, country) values ('Ekenäs', 'Finland');
insert into cities (city, country) values ('Honolulu', 'United States');
insert into cities (city, country) values ('Las Vegas', 'United States');
insert into cities (city, country) values ('Rochester', 'United States');
insert into cities (city, country) values ('Linköping', 'Sweden');
insert into cities (city, country) values ('Kristiansand S', 'Norway');
insert into cities (city, country) values ('Stockholm', 'Sweden');
insert into cities (city, country) values ('Arlington', 'United States');
insert into cities (city, country) values ('Guérande', 'France');
insert into cities (city, country) values ('Orléans', 'France');
insert into cities (city, country) values ('Omaha', 'United States');
insert into cities (city, country) values ('Västerås', 'Sweden');
insert into cities (city, country) values ('Bochum', 'Germany');
insert into cities (city, country) values ('Orsay', 'France');
insert into cities (city, country) values ('Arendal', 'Norway');
insert into cities (city, country) values ('Clearwater', 'United States');
insert into cities (city, country) values ('Mönsterås', 'Sweden');
insert into cities (city, country) values ('Carcassonne', 'France');
insert into cities (city, country) values ('Sunne', 'Sweden');
insert into cities (city, country) values ('Kristinehamn', 'Sweden');
insert into cities (city, country) values ('Alicante/Alacant', 'Spain');
insert into cities (city, country) values ('Houilles', 'France');
insert into cities (city, country) values ('Sainte-Geneviève-des-Bois', 'France');
insert into cities (city, country) values ('Evansville', 'United States');
insert into cities (city, country) values ('Pasadena', 'United States');
insert into cities (city, country) values ('Örnsköldsvik', 'Sweden');